apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: 'slack-notifications'
    groupBy: [alertname, job]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 3h

  receivers:
  - name: 'slack-notifications'
    slackConfigs:
    - apiURL:
        secret:
          name: alertmanager-slack-webhook
          key: webhookURL
      channel: "#alerts"
      sendResolved: true
      title: |
        [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}
      text: |
        *Severity:* `{{ .CommonLabels.severity }}`
        *Summary:* {{ (index .Alerts 0).Annotations.summary }}
